### ISSUE TITLE
Here are some question for you

### ISSUE THREAD

**Issue by NKUShaw** [kylematoba/lcnn#2]
Do the lcnn work on text dataset(nlp)such as Sentiment Analysis task? Due to the fact that ResNet and VGG are not suitable for the Sentiment Analysis, I plan to program TextCNN and TextCNN_lcnn but I failed to code it TvT.

**Comment by kylematoba** [comment]
Sure, the general recipe is not specific to any particular problem. Assuming you have a working recipe I suggest that you approach it in stages: introduce one of the spectral normalizations (e.g. on linear layers or batch norm or convolutions) only or low curvature nonlinearities only to start, and check that everything still works or at least exhibits expected properties before moving on to the next.
